# -*- coding: utf-8 -*-
"""Checking Password Strength.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ctl-yZsPIW6YSLK9wyjy0JHypxW7lylb

# Importing Required Libraries
"""

import warnings
warnings.simplefilter('ignore')

import random
import numpy as np
import pandas as pd
import seaborn as sns
import stremlit as st
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score

"""# Importing Data"""

data = pd.read_csv(r"Password Strength.csv", on_bad_lines='skip')

# we are using "on_bad_lines" to skip the line where it cannot
# be parsed or have some other issue that prevents them from being processed as expected.

data.head(10)

data.shape

data.isnull().sum()

data[data.isnull().any(axis=1)]

df = data.dropna()

df.isnull().sum()

df["strength"].value_counts()

sns.countplot(x = 'strength', data = df)

x = df['password']

y = df['strength']

x

y

x.isnull().sum()

def character(inputs):

    characters = []
    for i in inputs:
        characters.append(i)

    return characters

vec = TfidfVectorizer(tokenizer = character)
x = vec.fit_transform(x)

vec.vocabulary_

x.shape

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1000)

print(x.shape)
print(x_train.shape)
print(x_test.shape)

"""# Logistic Regression"""

lr = LogisticRegression()

lr.fit(x_train, y_train)

y_pred_test = lr.predict(x_test)

y_pred_train = lr.predict(x_train)

test_acc = accuracy_score(y_test, y_pred_test)

train_acc = accuracy_score(y_train, y_pred_train)

print(test_acc)

print(train_acc)

"""# Gradient Boosting"""

from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier()

gb_model.fit(x_train, y_train)

y_pred_gb = gb_model.predict(x_test)

test_acc_1 = accuracy_score(y_test, y_pred_gb)
test_acc_1

"""# Data Validation"""

user_inp = st.text_input("Enter password here")
user_inp = np.array([user_inp])
user_inp = vec.transform(user_inp)

y_pred = gb_model.predict(user_inp)

print(y_pred)
